services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - ${EXPOSE_PORT}:${APP_PORT}
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - ecomall

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecomall_development
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - ecomall

volumes:
  postgres_data:

networks:
  ecomall:
    driver: bridge
