// Code generated by MockGen. DO NOT EDIT.
// Source: app/modules/book_categories/repositories/repository.go
//
// Generated by this command:
//
//	mockgen -source=app/modules/book_categories/repositories/repository.go -destination=app/mocks/book_categories/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/1rhino/clean_architecture/app/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIBookCategoryRepo is a mock of IBookCategoryRepo interface.
type MockIBookCategoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIBookCategoryRepoMockRecorder
}

// MockIBookCategoryRepoMockRecorder is the mock recorder for MockIBookCategoryRepo.
type MockIBookCategoryRepoMockRecorder struct {
	mock *MockIBookCategoryRepo
}

// NewMockIBookCategoryRepo creates a new mock instance.
func NewMockIBookCategoryRepo(ctrl *gomock.Controller) *MockIBookCategoryRepo {
	mock := &MockIBookCategoryRepo{ctrl: ctrl}
	mock.recorder = &MockIBookCategoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBookCategoryRepo) EXPECT() *MockIBookCategoryRepoMockRecorder {
	return m.recorder
}

// CreateBookCategory mocks base method.
func (m *MockIBookCategoryRepo) CreateBookCategory(payload *models.BookCategoryParams) (*models.BookCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBookCategory", payload)
	ret0, _ := ret[0].(*models.BookCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBookCategory indicates an expected call of CreateBookCategory.
func (mr *MockIBookCategoryRepoMockRecorder) CreateBookCategory(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBookCategory", reflect.TypeOf((*MockIBookCategoryRepo)(nil).CreateBookCategory), payload)
}

// DeleteBookCategory mocks base method.
func (m *MockIBookCategoryRepo) DeleteBookCategory(bookCategoryID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBookCategory", bookCategoryID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBookCategory indicates an expected call of DeleteBookCategory.
func (mr *MockIBookCategoryRepoMockRecorder) DeleteBookCategory(bookCategoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBookCategory", reflect.TypeOf((*MockIBookCategoryRepo)(nil).DeleteBookCategory), bookCategoryID)
}

// GetBookCategories mocks base method.
func (m *MockIBookCategoryRepo) GetBookCategories() ([]*models.BookCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookCategories")
	ret0, _ := ret[0].([]*models.BookCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookCategories indicates an expected call of GetBookCategories.
func (mr *MockIBookCategoryRepoMockRecorder) GetBookCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookCategories", reflect.TypeOf((*MockIBookCategoryRepo)(nil).GetBookCategories))
}

// GetBookCategory mocks base method.
func (m *MockIBookCategoryRepo) GetBookCategory(id string) (*models.BookCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookCategory", id)
	ret0, _ := ret[0].(*models.BookCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookCategory indicates an expected call of GetBookCategory.
func (mr *MockIBookCategoryRepoMockRecorder) GetBookCategory(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookCategory", reflect.TypeOf((*MockIBookCategoryRepo)(nil).GetBookCategory), id)
}

// UpdateBookCategory mocks base method.
func (m *MockIBookCategoryRepo) UpdateBookCategory(bookCategory *models.BookCategory, payload *models.BookCategoryParams) (*models.BookCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBookCategory", bookCategory, payload)
	ret0, _ := ret[0].(*models.BookCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBookCategory indicates an expected call of UpdateBookCategory.
func (mr *MockIBookCategoryRepoMockRecorder) UpdateBookCategory(bookCategory, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBookCategory", reflect.TypeOf((*MockIBookCategoryRepo)(nil).UpdateBookCategory), bookCategory, payload)
}
